Cloudinary setup and modals update
pmunozs/FindYourMightyPet pull request #38
Opened 2022-11-01 18:16 UTC by pmunozs

- Cloudinary setup
- Update models

2022-11-01 19:37 UTC, henderson907 requested changes
Has the schema been updated to reflect the image tags? It doesn't load automatically in git hub

2022-11-01 19:37 UTC, henderson907 commented on app/models/user.rb
> +  has_one_attached :photo
why is the user model requiring a photo?

2022-11-01 19:37 UTC, henderson907 commented on app/views/pages/my_profile.html.erb
> +            <!-- <img class="card-img-top" src="https://source.unsplash.com/500x500/?<%= creature.name %>, scary" alt="Card image cap" /> -->
is this the same as the previous line but commented out? And so, is it needed?

2022-11-03 18:53 UTC, pmunozs commented on app/models/user.rb
> +  has_one_attached :photo
Removed

2022-11-03 18:54 UTC, pmunozs commented on app/views/pages/my_profile.html.erb
> +            <!-- <img class="card-img-top" src="https://source.unsplash.com/500x500/?<%= creature.name %>, scary" alt="Card image cap" /> -->
Removed

2022-11-03 19:05 UTC, merged